name: .NET

on: [push, pull_request]

jobs:
  build_and_tests:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore FAQ.API/
    - name: Build
      run: dotnet build FAQ.API/ --no-restore
    - name: Test
      run: dotnet test FAQ.API/ --no-build --verbosity normal
    - name: CountCodeLines-FAQ
      run: find FAQ.API -name '*.cs' | xargs wc -l
