using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FAQ.API.Helpers
{
    public static class LanguageHelper
    {
        private static readonly string defaultLanguage = "en_US";
        private static readonly string[] availableLanguages = {
            "af_ZA",
            "am_ET",
            "ar_AE",
            "ar_BH",
            "ar_DZ",
            "ar_EG",
            "ar_IQ",
            "ar_JO",
            "ar_KW",
            "ar_LB",
            "ar_LY",
            "ar_MA",
            "ar_OM",
            "ar_QA",
            "ar_SA",
            "ar_SY",
            "ar_TN",
            "ar_YE",
            "as_IN",
            "ba_RU",
            "be_BY",
            "bg_BG",
            "bn_BD",
            "bn_IN",
            "bo_CN",
            "br_FR",
            "ca_ES",
            "co_FR",
            "cs_CZ",
            "cy_GB",
            "da_DK",
            "de_AT",
            "de_CH",
            "de_DE",
            "de_LI",
            "de_LU",
            "dv_MV",
            "el_GR",
            "en_AU",
            "en_BZ",
            "en_CA",
            "en_GB",
            "en_IE",
            "en_IN",
            "en_JM",
            "en_MY",
            "en_NZ",
            "en_PH",
            "en_SG",
            "en_TT",
            "en_US",
            "en_ZA",
            "en_ZW",
            "es_AR",
            "es_BO",
            "es_CL",
            "es_CO",
            "es_CR",
            "es_DO",
            "es_EC",
            "es_ES",
            "es_GT",
            "es_HN",
            "es_MX",
            "es_NI",
            "es_PA",
            "es_PE",
            "es_PR",
            "es_PY",
            "es_SV",
            "es_US",
            "es_UY",
            "es_VE",
            "et_EE",
            "eu_ES",
            "fa_IR",
            "fi_FI",
            "fo_FO",
            "fr_BE",
            "fr_CA",
            "fr_CH",
            "fr_FR",
            "fr_LU",
            "fr_MC",
            "fy_NL",
            "ga_IE",
            "gd_GB",
            "gl_ES",
            "gu_IN",
            "he_IL",
            "hi_IN",
            "hr_BA",
            "hr_HR",
            "hu_HU",
            "hy_AM",
            "id_ID",
            "ig_NG",
            "ii_CN",
            "is_IS",
            "it_CH",
            "it_IT",
            "ja_JP",
            "ka_GE",
            "kk_KZ",
            "kl_GL",
            "km_KH",
            "kn_IN",
            "ko_KR",
            "ky_KG",
            "lb_LU",
            "lo_LA",
            "lt_LT",
            "lv_LV",
            "mi_NZ",
            "mk_MK",
            "ml_IN",
            "mn_MN",
            "mr_IN",
            "ms_BN",
            "ms_MY",
            "mt_MT",
            "nb_NO",
            "ne_NP",
            "nl_BE",
            "nl_NL",
            "nn_NO",
            "oc_FR",
            "or_IN",
            "pa_IN",
            "pl_PL",
            "ps_AF",
            "pt_BR",
            "pt_PT",
            "rm_CH",
            "ro_RO",
            "ru_RU",
            "rw_RW",
            "sa_IN",
            "se_FI",
            "se_NO",
            "se_SE",
            "si_LK",
            "sk_SK",
            "sl_SI",
            "sq_AL",
            "sv_FI",
            "sv_SE",
            "sw_KE",
            "ta_IN",
            "te_IN",
            "th_TH",
            "tk_TM",
            "tn_ZA",
            "tr_TR",
            "tt_RU",
            "ug_CN",
            "uk_UA",
            "ur_PK",
            "vi_VN",
            "wo_SN",
            "xh_ZA",
            "yo_NG",
            "zh_CN",
            "zh_HK",
            "zh_MO",
            "zh_SG",
            "zh_TW",
            "zu_ZA"
            };

        /// <summary>
        /// Check if a local language is available 
        /// </summary>
        /// <param name="language">Language code</param>
        /// <returns>Valid language local code</returns>
        public static void CheckLanguage(ref string language)
        {
            if (language?.Length != 5 || !availableLanguages.Contains(language))
                language = defaultLanguage;
        }

        /// <summary>
        /// Check if a local language is available 
        /// </summary>
        /// <param name="language">Language code</param>
        /// <returns>Valid language local code</returns>
        public static bool IsLanguageOK(string language)
        {
            if (language?.Length != 5 || !availableLanguages.Contains(language))
                return false;

            return true;
        }
    }
}
